[build]
  command = "npm run build"
  publish = ".next"
  environment = { NODE_VERSION = "18", NEXT_TELEMETRY_DISABLED = "1", NODE_OPTIONS = "--max_old_space_size=4096" }

[[plugins]]
  package = "@netlify/plugin-nextjs"

# Handle SPA routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Handle API redirects if needed
[[redirects]]
  from = "/api/*"
  to = "https://language-exchange-api.onrender.com/api/:splat"
  status = 200
  force = true
